/* Generated By:JavaCC: Do not edit this line. gclConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gclConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int tPROGRAMA = 8;
  /** RegularExpression Id. */
  int tENTACAR = 9;
  /** RegularExpression Id. */
  int tCARAENT = 10;
  /** RegularExpression Id. */
  int tESCRIBIR = 11;
  /** RegularExpression Id. */
  int tESCRIBIR_LIN = 12;
  /** RegularExpression Id. */
  int tLEER = 13;
  /** RegularExpression Id. */
  int tLEER_LIN = 14;
  /** RegularExpression Id. */
  int tSTRING = 15;
  /** RegularExpression Id. */
  int tCHAR = 16;
  /** RegularExpression Id. */
  int tREF = 17;
  /** RegularExpression Id. */
  int tINTEGER = 18;
  /** RegularExpression Id. */
  int tCHARACTER = 19;
  /** RegularExpression Id. */
  int tBOOLEAN = 20;
  /** RegularExpression Id. */
  int tCOMA = 21;
  /** RegularExpression Id. */
  int tSEMICOLON = 22;
  /** RegularExpression Id. */
  int tUNDERSCORE = 23;
  /** RegularExpression Id. */
  int tASSIGN = 24;
  /** RegularExpression Id. */
  int tSINGLE_QUOTE = 25;
  /** RegularExpression Id. */
  int tOPENING_SQUARE_BRACKET = 26;
  /** RegularExpression Id. */
  int tCLOSING_SQUARE_BRACKET = 27;
  /** RegularExpression Id. */
  int tSELECTION = 28;
  /** RegularExpression Id. */
  int tEND_SELECTION = 29;
  /** RegularExpression Id. */
  int tCASE = 30;
  /** RegularExpression Id. */
  int tCOLON = 31;
  /** RegularExpression Id. */
  int tOTHERWISE = 32;
  /** RegularExpression Id. */
  int tITERATION = 33;
  /** RegularExpression Id. */
  int tEND_ITERATION = 34;
  /** RegularExpression Id. */
  int tNO_INSTRUCTION = 35;
  /** RegularExpression Id. */
  int tOPENING_PARENTHESIS = 36;
  /** RegularExpression Id. */
  int tCLOSING_PARENTHESIS = 37;
  /** RegularExpression Id. */
  int tBEGGINING = 38;
  /** RegularExpression Id. */
  int tEND = 39;
  /** RegularExpression Id. */
  int tPLUS = 40;
  /** RegularExpression Id. */
  int tMINUS = 41;
  /** RegularExpression Id. */
  int tTIMES = 42;
  /** RegularExpression Id. */
  int tDIVIDE = 43;
  /** RegularExpression Id. */
  int tMOD = 44;
  /** RegularExpression Id. */
  int tAND = 45;
  /** RegularExpression Id. */
  int tOR = 46;
  /** RegularExpression Id. */
  int tNOT = 47;
  /** RegularExpression Id. */
  int tGT = 48;
  /** RegularExpression Id. */
  int tGE = 49;
  /** RegularExpression Id. */
  int tLT = 50;
  /** RegularExpression Id. */
  int tLE = 51;
  /** RegularExpression Id. */
  int tEQUAL = 52;
  /** RegularExpression Id. */
  int tNOTEQUAL = 53;
  /** RegularExpression Id. */
  int tDOT = 54;
  /** RegularExpression Id. */
  int tCONSTANT = 55;
  /** RegularExpression Id. */
  int tTRUE = 56;
  /** RegularExpression Id. */
  int tFALSE = 57;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 58;
  /** RegularExpression Id. */
  int tOTHER = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<LETTER>",
    "<DIGIT>",
    "\"Programa\"",
    "\"entAcar\"",
    "\"carAent\"",
    "\"tescribir\"",
    "\"tescribir_lin\"",
    "\"tleer\"",
    "\"leer_lin\"",
    "<tSTRING>",
    "<tCHAR>",
    "\"ref\"",
    "\"entero\"",
    "\"caracter\"",
    "\"booleano\"",
    "\",\"",
    "\";\"",
    "\"_\"",
    "\":=\"",
    "\"\\\'\"",
    "\"[\"",
    "\"]\"",
    "\"Sel\"",
    "\"Fsel\"",
    "\"caso\"",
    "\":\"",
    "\"dlc\"",
    "\"Mq\"",
    "\"FMq\"",
    "\"nada\"",
    "\"(\"",
    "\")\"",
    "\"Principio\"",
    "\"Fin\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"<>\"",
    "\".\"",
    "<tCONSTANT>",
    "\"verdadero\"",
    "\"falso\"",
    "<tIDENTIFICADOR>",
    "<tOTHER>",
  };

}
