/* Generated By:JavaCC: Do not edit this line. gcl.java */
package traductor;

import lib.symbolTable.*;
import lib.symbolTable.exceptions.*;

import java.util.*;

public class gcl implements gclConstants {
    // tabla de símbolos global
        static SymbolTable st;

   public static void main(String[] args) {
           gcl parser = null;

           try {
           st = new SymbolTable();

                   if(args.length == 0) {
                           parser = new gcl(System.in);
                   }
                   else {
                           parser = new gcl(new java.io.FileInputStream(args[0]));
                   }
                   //Programa es el símbolo inicial de la gramática
                   parser.Programa();
                   //...
                   System.out.println("***** An\u00e1lisis terminado con \u00e9xito *****");
           }
           catch (java.io.FileNotFoundException e) {
                   System.out.println ("Fichero " + args[0] + " no encontrado.");
           }
           catch (TokenMgrError e) {
                   System.out.println("LEX_ERROR: " + e.getMessage());
           }
           catch (Exception e) {
                        System.out.println("Ha ocurrido una excepci\u00f3n: " + e.getMessage());
           }
        }

    // inserta todos los símbolos de "lVars" de tipo "aT" y los marca como ref si "isRef",
    // auxiliar para "parametros_declaraciones" (los parámetros de la declaración de una función/procedimiento)
    private static void insertSymbols(AtribTipo aT, boolean isRef, ArrayList<String> lVars) {
    for (String id : lVars) {
        try {
            Symbol sV = null;
            if (aT.isArray) {
                sV = new SymbolArray(id, 0, aT.size-1, aT.type);
            } else {
                switch(aT.type) {
                    case INT:
                        sV = new SymbolInt(id); break;
                    case BOOL:
                        sV = new SymbolBool(id); break;
                    case CHAR:
                        sV = new SymbolChar(id); break;
                    default:
                        System.out.println("Error: tipo no definido para variable \"" + id + "\".");
                }
            }
            if (sV != null) {
                sV.parClass = isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL;
                st.insertSymbol(sV);
                System.out.println("[TABLA DE S\u00cdMBOLOS] Insertado " + sV.toString());
            }
        } catch (AlreadyDefinedSymbolException e) {
            System.out.println("Error: Identificador ya existe: \"" + id + "\"");
        }
    }
}

// --- INICIO DE programa.jj ---
  static final public void Programa() throws ParseException {
    jj_consume_token(tPROGRAMA);
    jj_consume_token(tIDENTIFICADOR);
    label_1:
    while (true) {
      if (jj_2_1(3)) {
        ;
      } else {
        break label_1;
      }
      declaracion_variables();
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_2;
      }
      declaracion_procs_funcs();
    }
    jj_consume_token(tBEGGINING);
    instrucciones();
    jj_consume_token(tEND);
  }

// --- INICIO DE tipos.jj ---
  static final public AtribTipo tipo() throws ParseException {
    AtribTipo aT;
    if (jj_2_2(2)) {
      aT = tipoArray();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
        aT = tipoEscalar();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return aT;}
    throw new Error("Missing return statement in function");
  }

  static final public AtribTipo tipoEscalar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tINTEGER:
      jj_consume_token(tINTEGER);
                      {if (true) return new AtribTipo(Symbol.Types.INT );}
      break;
    case tCHARACTER:
      jj_consume_token(tCHARACTER);
                      {if (true) return new AtribTipo(Symbol.Types.CHAR);}
      break;
    case tBOOLEAN:
      jj_consume_token(tBOOLEAN);
                      {if (true) return new AtribTipo(Symbol.Types.BOOL);}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public AtribTipo tipoArray() throws ParseException {
    Symbol.Types t;
    AtribExp aE;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tCHARACTER:
      jj_consume_token(tCHARACTER);
                       t = Symbol.Types.CHAR;
      break;
    case tBOOLEAN:
      jj_consume_token(tBOOLEAN);
                       t = Symbol.Types.BOOL;
      break;
    case tINTEGER:
      jj_consume_token(tINTEGER);
                       t = Symbol.Types.INT;
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(tOPENING_SQUARE_BRACKET);
    aE = expresion_simple();
    jj_consume_token(tCLOSING_SQUARE_BRACKET);
        {if (true) return new AtribTipo(t, Integer.parseInt(aE.image));}
    throw new Error("Missing return statement in function");
  }

// --- INICIO DE variables.jj ---
  static final public void declaracion_variables() throws ParseException {
    label_3:
    while (true) {
      declaracion();
      if (jj_2_3(3)) {
        ;
      } else {
        break label_3;
      }
    }
  }

  static final public ArrayList<String> lista_ids() throws ParseException {
    ArrayList<String> lVars = new ArrayList<String>();
    Token t;
    t = jj_consume_token(tIDENTIFICADOR);
      lVars.add(t.image);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tCOMA:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      jj_consume_token(tCOMA);
      t = jj_consume_token(tIDENTIFICADOR);
          lVars.add(t.image);
    }
      {if (true) return lVars;}
    throw new Error("Missing return statement in function");
  }

  static final public void declaracion() throws ParseException {
    AtribTipo aT;
    ArrayList<String> lVars;
    aT = tipo();
    lVars = lista_ids();
    jj_consume_token(tSEMICOLON);
        for(String id : lVars) {
            try {
                Symbol sV = null;
                if(aT.isArray) {
                    sV = new SymbolArray(id, 0, aT.size-1, aT.type);
                } else {
                    switch(aT.type) {
                        case INT:
                            sV = new SymbolInt(id); break;
                        case BOOL:
                            sV = new SymbolBool(id); break;
                        case CHAR:
                            sV = new SymbolChar(id); break;
                        default:
                            System.out.println("Error: tipo no definido para variable \"" +
                                id + "\".");
                    }
                }
                if(sV != null) {
                    st.insertSymbol(sV);
                    System.out.println("[TABLA DE S\u00cdMBOLOS] Insertado " + sV.toString());
                }
            } catch(AlreadyDefinedSymbolException e) {
                System.out.println("Error: ya existe variable con identificador \"" +
                    id + "\".");
            }
        }
  }

  static final public void asignacion() throws ParseException {
  System.out.println("Asignacion");
    jj_consume_token(tIDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tOPENING_SQUARE_BRACKET:
      jj_consume_token(tOPENING_SQUARE_BRACKET);
      expresion_simple();
      jj_consume_token(tCLOSING_SQUARE_BRACKET);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(tASSIGN);
    expresion();
    jj_consume_token(tSEMICOLON);
  }

// --- INICIO DE expresiones.jj ---
/**
 * Orden de prioridad de expansión (cuanto más izquierda, más prioridad).
 * primario - factor - termino - expresion_simple - relacion - expresion
 */
  static final public AtribExp primario() throws ParseException {
    Token t;
    AtribExp ae;
    Symbol s = null;
    SymbolFunction s_func;
    SymbolArray s_array;
        System.out.println("Entrando en primario");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tENTACAR:
      entAcar();
          {if (true) return new AtribExp(Symbol.Types.CHAR, null, false, false);}
      break;
    case tCARAENT:
      carAent();
          {if (true) return new AtribExp(Symbol.Types.INT, null, false, false);}
      break;
    default:
      jj_la1[6] = jj_gen;
      if (jj_2_4(2)) {
        // Para distinguirlo de un array o variable.
                t = jj_consume_token(tIDENTIFICADOR);
        jj_consume_token(tOPENING_PARENTHESIS);
        parametros_llamada_funcion();
        jj_consume_token(tCLOSING_PARENTHESIS);
            try {
                s = st.getSymbol(t.image);
            } catch (SymbolNotFoundException e) {
                /**
                 * Lanzar una excepción si la sintaxis utilizada es la de la llamada a una función pero el identificador semánticamente no existe.
                 */
                System.out.println("Error: El identificador '" + t.image + "' no est\u00e1 definido.");
                {if (true) return null;}
            }
            /**
             * Lanzar una excepción si la sintaxis utilizada es la de la llamada a una función pero el identificador semánticamente no es una función.
             */
            if (s.type != Symbol.Types.FUNCTION) {
                System.out.println("Error: Se esperaba que '" + t.image + "' fuera una funci\u00f3n (o procedimiento), pero se encontr\u00f3: " + s.type + ".");
            }
            /**
             * Devolver una expresión del tipo de retorno de la función y valor indefinido (no evaluable estáticamente).
             */
            s_func = (SymbolFunction) s;
            {if (true) return new AtribExp(s_func.returnType, null, false, false);} // Marcar el atributo variable a falso porque las funciones devuelven constantes.

      } else if (jj_2_5(2)) {
        // Para distinguirlo del acceso a una variable.
                t = jj_consume_token(tIDENTIFICADOR);
        jj_consume_token(tOPENING_SQUARE_BRACKET);
        ae = expresion();
        jj_consume_token(tCLOSING_SQUARE_BRACKET);
            try {
                s = st.getSymbol(t.image);
            } catch (SymbolNotFoundException e) {
                /**
                 * Lanzar una excepción si la sintaxis utilizada es la de un array pero el identificador semánticamente no existe.
                 */
                System.out.println("Error: El identificador '" + t.image + "' no est\u00e1 definido.");
                {if (true) return null;}
            }
            /**
             * Lanzar una excepción si la sintaxis utilizada es la de un array pero el identificador semánticamente no es un array.
             */
            if (s.type != Symbol.Types.ARRAY) {
                System.out.println("Error: Se esperaba que '" + t.image + "' fuera un array, pero se encontr\u00f3: " + s.type + ".");
            }
            /**
             * Lanzar una excepción si el tipo del valor de acceso al array no es un entero.
             */
            if (ae.type != Symbol.Types.INT) {
                System.out.println("Error: Se esperaba que el \u00edndice del array fuera un entero, pero se evalu\u00f3: tipo " + ae.type + " con valor '" + ae.image + "'.");
            }
            s_array = (SymbolArray) s; // Para acceder al campo maxInd
            /**
             * Optimización: si el valor de acceso al vector es un entero y es constante, comprobar estáticamente que es válido.
             * Lanzar una excepción si no es válido.
             */
            if (ae.isConst && Integer.valueOf(ae.image) > s_array.maxInd) {
                System.out.println("Error: El \u00edndice " + ae.image + " es demasiado grande para el vector " + t.image + " de tama\u00f1o " + (s_array.maxInd + 1) + "'.");
            }
            /**
             * Lanzar una excepción si el valor de acceso al vector es un entero no constante.
             */
            Symbol.Types elemType = s_array.baseType;
            {if (true) return new AtribExp(elemType, null, true, ae.isConst && s.constant);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tIDENTIFICADOR:
          /**
                   * Caso: acceso a una variable.
                   */
                  t = jj_consume_token(tIDENTIFICADOR);
            try {
                s = st.getSymbol(t.image);
                String image = t.image;
                {if (true) return new AtribExp(s.type, null, true, false);} // Valor null por no ser evaluable en tiempo de compilación (no existen variables constantes en gcl).
            } catch (SymbolNotFoundException e) {
                /**
                 * Lanzar una excepción si la sintaxis utilizada es la de acceso a una variable pero semánticamente el identificador no existe.
                 */
                System.out.println("Error: El identificador '" + t.image + "' no est\u00e1 definido.");
                {if (true) throw new SymbolNotFoundException("Error: El identificador '" + t.image + "' no est\u00e1 definido.");}
            }
          break;
        case tCONSTANT:
          /**
                   * Caso: constante int.
                   */
                  t = jj_consume_token(tCONSTANT);
            {if (true) return new AtribExp(Symbol.Types.INT, t.image, false, true);}
          break;
        case tCHAR:
          /**
                   * Caso: constante char.
                   */
                  t = jj_consume_token(tCHAR);
            {if (true) return new AtribExp(Symbol.Types.CHAR, t.image, false, true);}
          break;
        case tSTRING:
          /**
                   * Caso: constante string.
                   */
                  t = jj_consume_token(tSTRING);
            {if (true) return new AtribExp(Symbol.Types.STRING, t.image, false, true);}
          break;
        case tTRUE:
          /**
                   * Caso: constante bool con valor true.
                   */
                  t = jj_consume_token(tTRUE);
            {if (true) return new AtribExp(Symbol.Types.BOOL, t.image, false, true);}
          break;
        case tFALSE:
          /**
                   * Caso: constante bool con valor false.
                   */
                  t = jj_consume_token(tFALSE);
            {if (true) return new AtribExp(Symbol.Types.BOOL, t.image, false, true);}
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
        System.out.println("Error: Saliendo de primario por caso no identificado (\u00bfinaccesible?)");
        {if (true) return new AtribExp(Symbol.Types.UNDEFINED, null, false, false);}
    throw new Error("Missing return statement in function");
  }

  static final public AtribExp factor() throws ParseException {
    System.out.println("Entrando en factor");
    Token op = null;
    AtribExp ae;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tPLUS:
    case tMINUS:
    case tNOT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tNOT:
        op = jj_consume_token(tNOT);
        break;
      case tPLUS:
        op = jj_consume_token(tPLUS);
        break;
      case tMINUS:
        op = jj_consume_token(tMINUS);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tOPENING_PARENTHESIS:
      jj_consume_token(tOPENING_PARENTHESIS);
      ae = expresion();
      jj_consume_token(tCLOSING_PARENTHESIS);
      break;
    case tENTACAR:
    case tCARAENT:
    case tTRUE:
    case tFALSE:
    case tSTRING:
    case tCHAR:
    case tCONSTANT:
    case tIDENTIFICADOR:
      ae = primario();
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        if (op != null) {
            /**
             * Lanzar una excepción si el operador no es válido.
             */
            if ((op.image.equals("!") && ae.type != Symbol.Types.BOOL) ||
                ((op.image.equals("+") || op.image.equals("-")) && ae.type != Symbol.Types.INT)) {
                System.out.println (
                    "Error: El operador '" + op.image + "' requiere un valor del tipo adecuado, pero se evalu\u00f3: "
                    + "tipo " + ae.type + " con valor '" + ae.image + "'."
                );
            }

            boolean isConst = ae.isConst;
            String val = null;

            /**
             * Evaluar la expresión recibida si es constante y tiene delante algún operador.
             */
            if (isConst) {
                if (op.image.equals("!")) {
                    val = String.valueOf(!Boolean.parseBoolean(ae.image));
                } else {
                    int num = Integer.parseInt(ae.image);
                    val = op.image.equals("-") ? String.valueOf(-num) : String.valueOf(num);
                }
            }

            /**
             * Devolver una expresión del tipo correspondiente, con el valor evaluado si es constante.
             */
            System.out.println("Saliendo de factor tras operador " + op.image +
                               (isConst ? " con resultado constante" : " con resultado no constante"));
            {if (true) return new AtribExp(op.image.equals("!") ? Symbol.Types.BOOL : Symbol.Types.INT, val, false, isConst);}
        }

        /**
         * Devolver exactamente la expresión recibida si no tiene ningún operador delante, op == null.
         */
        System.out.println("Saliendo de factor con expresi\u00f3n primaria");
        {if (true) return ae;}
    throw new Error("Missing return statement in function");
  }

  static final public AtribExp termino() throws ParseException {
    System.out.println("Entrando en termino");
    AtribExp left, right;
    Token op;
    left = factor();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tTIMES:
      case tDIVIDE:
      case tMOD:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      op = operador_multiplicativo();
      right = factor();
            /**
             * Lanzar una excepción si los 2 factores no son del mismo tipo.
             */
            if (left.type != Symbol.Types.INT || right.type != Symbol.Types.INT) {
                System.out.println(
                    "Error: Los operadores multiplicativos requieren valores enteros. Se evalu\u00f3: "
                    + "left.type = " + left.type + " con valor '" + left.image
                    + "', right.type = " + right.type + " con valor '" + right.image + "'."
                );
            }
            boolean isConst = left.isConst && right.isConst;
            String val = null;

            /**
             * Evaluar el termino si los 2 factores son constantes.
             */
            if (isConst) {
                int l = Integer.parseInt(left.image);
                int r = Integer.parseInt(right.image);

                switch (op.image) {
                    case "*":
                        val = String.valueOf(l * r);
                        break;
                    case "/":
                        val = (r != 0) ? String.valueOf(l / r) : "0";
                        break;
                    case "MOD":
                        val = String.valueOf(l % r);
                        break;
                }
            }

            left = new AtribExp(Symbol.Types.INT, val, false, isConst);
    }
        System.out.println("Saliendo de termino");
        {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  static final public AtribExp expresion_simple() throws ParseException {
    System.out.println("Entrando en expresion_simple");
    AtribExp left, right;
    Token op;
    boolean isConst;
    left = termino();
        isConst = left.isConst;
    label_6:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPLUS:
        op = jj_consume_token(tPLUS);
        break;
      case tMINUS:
        op = jj_consume_token(tMINUS);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = termino();
            /**
             * Lanzar una excepción si los 2 operandos no son del mismo tipo.
             */
            if (left.type != right.type) {
                System.out.println(
                    "Error: Los operandos para el operador '" + op.image
                    + "' deben ser del mismo tipo. Se evalu\u00f3: left.type = " + left.type
                    + " con valor '" + left.image + "', right.type = " + right.type
                    + " con valor '" + right.image + "'."
                );
            }

            /**
             * Lanzar una excepción si los 2 operandos no son de tipo integer.
             */
            if (left.type != Symbol.Types.INT || right.type != Symbol.Types.INT) {
                System.out.println(
                    "Error: Los operadores de expresiones requieren valores enteros. Se evalu\u00f3: "
                    + "left.type = " + left.type + " con valor '" + left.image
                    + "', right.type = " + right.type + " con valor '" + right.image + "'. Al menos uno de ellos no es booleano."
                );
            }

            isConst = isConst && right.isConst;

            /**
             * Evaluar la expresión simple si los 2 terminos son constantes.
             */
            if (isConst) {
                int l = Integer.parseInt(left.image);
                int r = Integer.parseInt(right.image);

                left.image = op.image.equals("+") ? String.valueOf(l + r): String.valueOf(l - r);
            } else {
                left.image = null;
            }

            left.isConst = isConst;
    }
        System.out.println("Saliendo de expresion_simple");
        {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  static final public AtribExp relacion() throws ParseException {
    System.out.println("Entrando en relacion");
    AtribExp left, right = null;
    Token op = null;
    left = expresion_simple();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tGT:
    case tGE:
    case tLT:
    case tLE:
    case tEQUAL:
    case tNOTEQUAL:
      op = operador_relacional();
      right = expresion_simple();
            /**
             * Lanzar una excepción si los 2 operandos no son del mismo tipo.
             */
            if (left.type != right.type) {
                System.out.println(
                    "Error: Los operandos para el operador '" + op.image
                    + "' deben ser del mismo tipo. Se evalu\u00f3: left.type = " + left.type
                    + " con valor '" + left.image + "', right.type = " + right.type
                    + " con valor '" + right.image + "'."
                );
            }

            /**
             * Lanzar una excepción si los 2 operandos no son de tipo booleando y el operador los requiere.
             */
            if (op.image.matches("=|!=") && (left.type != Symbol.Types.BOOL || right.type != Symbol.Types.BOOL)) {
                System.out.println(
                    "Error: Los operandos para el operador '" + op.image
                    + "' deben ser del mismo tipo. Se evalu\u00f3: left.type = " + left.type
                    + " con valor '" + left.image + "', right.type = " + right.type
                    + " con valor '" + right.image + "'."
                );
            }

            /**
             * Lanzar una excepción si los 2 operandos no son de tipo entero y el operador los requiere.
             */
            if (op.image.matches("<|<=|>|>=") && (left.type != Symbol.Types.INT || right.type != Symbol.Types.INT))
                System.out.println(
                    "Error: Los operadores relacionales requieren valores enteros. Se evalu\u00f3: "
                    + "left.type = " + left.type + " con valor '" + left.image
                    + "', right.type = " + right.type + " con valor '" + right.image + "'."
                );

            boolean isConst = left.isConst && right.isConst;
            String val = null;

            /**
             * Evaluar la relacion si las 2 expresiones simples son constantes.
             */
            if (isConst) {
                boolean result = false;

                switch (left.type) {
                    case INT:
                        int l = Integer.parseInt(left.image);
                        int r = Integer.parseInt(right.image);
                        switch (op.image) {
                            case "=": result = (l == r); break;
                            case "!=": result = (l != r); break;
                            case "<": result = (l < r); break;
                            case "<=": result = (l <= r); break;
                            case ">": result = (l > r); break;
                            case ">=": result = (l >= r); break;
                        }
                        break;

                    case BOOL:
                        boolean bl = Boolean.parseBoolean(left.image);
                        boolean br = Boolean.parseBoolean(right.image);
                        result = op.image.equals("=") ? (bl == br) : (bl != br);
                        break;
                }

                val = String.valueOf(result);
            }

            left = new AtribExp(Symbol.Types.BOOL, val, false, isConst);
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
        System.out.println("Saliendo de relacion");
        {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  static final public AtribExp expresion() throws ParseException {
    System.out.println("Entrando en expresion");
    AtribExp left, right;
    Token op;
    boolean isConst;
    boolean left_type, right_type;
    left = relacion();
        isConst = left.isConst;
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tAND:
      case tOR:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tAND:
        op = jj_consume_token(tAND);
        break;
      case tOR:
        op = jj_consume_token(tOR);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = relacion();
            /**
             * Lanzar una excepción si los 2 operandos no son del mismo tipo.
             */
            if (left.type != right.type) {
                System.out.println(
                    "Error: Los operandos para el operador '" + op.image
                    + "' deben ser del mismo tipo. Se evalu\u00f3: left.type = " + left.type
                    + " con valor '" + left.image + "', right.type = " + right.type
                    + " con valor '" + right.image + "'."
                );
            }

            /**
             * Lanzar una excepción si los 2 operandos no son de tipo booleando.
             */
            if (left.type != Symbol.Types.BOOL || right.type != Symbol.Types.BOOL) {
                System.out.println(
                    "Error: Los operadores de expresiones requieren valores booleanos. Se evalu\u00f3: "
                    + "left.type = " + left.type + " con valor '" + left.image
                    + "', right.type = " + right.type + " con valor '" + right.image + "'. Al menos uno de ellos no es booleano."
                );
            }

            isConst = isConst && right.isConst;

            /**
             * Evaluar la expresion si las 2 relaciones son constantes.
             */
            if (isConst) {
                boolean l = Boolean.parseBoolean(left.image);
                boolean r = Boolean.parseBoolean(right.image);

                left.image = op.image.equals("&")
                    ? String.valueOf(l && r)
                    : String.valueOf(l || r);
            } else {
                left.image = null;
            }

            left.isConst = isConst;
    }
        System.out.println("Saliendo de expresion");
        {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  static final public void lista_una_o_mas_exps() throws ParseException {
    label_8:
    while (true) {
      expresion();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tENTACAR:
      case tCARAENT:
      case tTRUE:
      case tFALSE:
      case tSTRING:
      case tCHAR:
      case tCONSTANT:
      case tOPENING_PARENTHESIS:
      case tPLUS:
      case tMINUS:
      case tNOT:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_8;
      }
    }
  }

  static final public Token operador_multiplicativo() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tTIMES:
      t = jj_consume_token(tTIMES);
                      {if (true) return t;}
      break;
    case tDIVIDE:
      t = jj_consume_token(tDIVIDE);
                      {if (true) return t;}
      break;
    case tMOD:
      t = jj_consume_token(tMOD);
                      {if (true) return t;}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token operador_relacional() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tEQUAL:
      t = jj_consume_token(tEQUAL);
                      {if (true) return t;}
      break;
    case tNOTEQUAL:
      t = jj_consume_token(tNOTEQUAL);
                      {if (true) return t;}
      break;
    case tLT:
      t = jj_consume_token(tLT);
                      {if (true) return t;}
      break;
    case tLE:
      t = jj_consume_token(tLE);
                      {if (true) return t;}
      break;
    case tGT:
      t = jj_consume_token(tGT);
                      {if (true) return t;}
      break;
    case tGE:
      t = jj_consume_token(tGE);
                      {if (true) return t;}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// --- INICIO DE funciones.jj ---
  static final public void declaracion_procs_funcs() throws ParseException {
  System.out.println("Declaraci\u00f3n de procedimientos/funciones");
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tIDENTIFICADOR:
        declaracion_proc();
        break;
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
        declaracion_func();
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_9;
      }
    }
  }

  static final public void declaracion_proc() throws ParseException {
    System.out.println("Declaraci\u00f3n de procedimiento");
    Symbol sFunc;
    Token t;
    ArrayList<Symbol> parametros = new ArrayList<Symbol>();
    t = jj_consume_token(tIDENTIFICADOR);
    jj_consume_token(tOPENING_PARENTHESIS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tINTEGER:
    case tCHARACTER:
    case tBOOLEAN:
      parametros = parametros_declaraciones();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(tCLOSING_PARENTHESIS);
        try {
            sFunc = new SymbolProcedure(t.image, parametros);
            st.insertSymbol(sFunc);
            st.insertBlock();
            for(Symbol param : parametros) {
                st.insertSymbol(param);
                System.out.println("Variable insertada en el procedimiento: \"" + t.image + "\".");
            }
        }
        catch (AlreadyDefinedSymbolException e) {
            System.out.println("Error: ya existe procedimiento con identificador \"" + t.image + "\".");
        }
    label_10:
    while (true) {
      if (jj_2_7(3)) {
        ;
      } else {
        break label_10;
      }
      declaracion_variables();
    }
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_11;
      }
      declaracion_procs_funcs();
    }
    jj_consume_token(tBEGGINING);
    instrucciones();
    jj_consume_token(tEND);
      st.removeBlock();
  }

  static final public void declaracion_func() throws ParseException {
    System.out.println("Declaraci\u00f3n de funci\u00f3n");
    Symbol sFunc;
    Token t;
    AtribTipo aT;
    ArrayList<Symbol> parametros = new ArrayList<Symbol>();
    aT = tipoEscalar();
    t = jj_consume_token(tIDENTIFICADOR);
        sFunc = null;
        switch (aT.type) {
            case INT:
                sFunc = new SymbolInt(t.image);
                break;
            case BOOL:
                sFunc = new SymbolBool(t.image);
                break;
            case CHAR:
                sFunc = new SymbolChar(t.image);
                break;
            default:
                System.out.println("Error: tipo no definido para funci\u00f3n \"" + t.image + "\".");
        }
    jj_consume_token(tOPENING_PARENTHESIS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tINTEGER:
    case tCHARACTER:
    case tBOOLEAN:
      parametros = parametros_declaraciones();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(tCLOSING_PARENTHESIS);
        try {
            sFunc = new SymbolFunction(t.image, parametros, aT.type);
            st.insertSymbol(sFunc);
            st.insertBlock();
            System.out.println(st.toString());

            for(Symbol param : parametros) {
                st.insertSymbol(param);
                System.out.println("Variable insertada en la funci\u00f3n: \"" + t.image + "\".");
            }
        }
        catch (AlreadyDefinedSymbolException e) {
            System.out.println("Error: ya existe funci\u00f3n con identificador \"" + t.image + "\".");
        }
    label_12:
    while (true) {
      if (jj_2_8(3)) {
        ;
      } else {
        break label_12;
      }
      declaracion_variables();
    }
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_13;
      }
      declaracion_procs_funcs();
    }
    jj_consume_token(tBEGGINING);
    instrucciones();
    jj_consume_token(tEND);
      st.removeBlock();
  }

  static final public void llamar_funcion() throws ParseException {
    ArrayList<AtribExp> lPar = new ArrayList<AtribExp>();
    Symbol fun;
    Token t;
    System.out.println("Llamar funci\u00f3n");
    t = jj_consume_token(tIDENTIFICADOR);
    jj_consume_token(tOPENING_PARENTHESIS);
    lPar = parametros_llamada_funcion();
        try {
            fun = st.getSymbol(t.image);

            if(fun.type == Symbol.Types.FUNCTION) {
                SymbolFunction aux =(SymbolFunction)fun;
                for(int i = 0; i < lPar.size(); ++i) {
                    if(lPar.get(i).type != aux.parList.get(i).type) { // tipos no coinciden
                        String errorMsg = String.format("Par\u00e1metro no compatible con valor dado. Tipo esperado: %s. Tipo recibido: %s",
                            aux.parList.get(i).type, lPar.get(i).type);
                        System.out.println("Error en llamada a funci\u00f3n: " + errorMsg);
                    }
                    if(aux.parList.get(i).parClass == Symbol.ParameterClass.REF && !lPar.get(i).isVar) { // valores por referencia
                        String errorMsg = String.format("Par\u00e1metro por referencia. Espera variable.",
                            aux.parList.get(i).type, lPar.get(i).type);
                        System.out.println("Error en llamada a funci\u00f3n: " + errorMsg);
                    }
                }
            } else if(fun.type == Symbol.Types.PROCEDURE) {
                SymbolProcedure aux =(SymbolProcedure)fun;
                for(int i = 0; i < lPar.size(); ++i) {
                    if(lPar.get(i).type != aux.parList.get(i).type) { // tipos no coinciden
                        String errorMsg = String.format("Par\u00e1metro no compatible con valor dado. Tipo esperado: %s. Tipo recibido: %s",
                            aux.parList.get(i).type, lPar.get(i).type);
                        System.out.println("Error en llamada a funci\u00f3n: " + errorMsg);
                    }
                    if(aux.parList.get(i).parClass == Symbol.ParameterClass.REF && !lPar.get(i).isVar) { // valores por referencia
                        String errorMsg = String.format("Par\u00e1metro por referencia. Espera variable.",
                            aux.parList.get(i).type, lPar.get(i).type);
                        System.out.println("Error en llamada a funci\u00f3n: " + errorMsg);
                    }
                }
            }

        } catch(SymbolNotFoundException e) {
            System.out.println("Error en llamada a funci\u00f3n: no existe s\u00edmbolo con nombre \"" + t.image + "\".");
        }
    jj_consume_token(tCLOSING_PARENTHESIS);
    jj_consume_token(tSEMICOLON);
  }

  static final public ArrayList<AtribExp> parametros_llamada_funcion() throws ParseException {
    ArrayList<AtribExp> lpar = new ArrayList<AtribExp>();
    AtribExp ae = null;
    System.out.println("Par\u00e1metros llamada funci\u00f3n");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tENTACAR:
    case tCARAENT:
    case tTRUE:
    case tFALSE:
    case tSTRING:
    case tCHAR:
    case tCONSTANT:
    case tOPENING_PARENTHESIS:
    case tPLUS:
    case tMINUS:
    case tNOT:
    case tIDENTIFICADOR:
      ae = expresion();
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
        if(ae != null)
            lpar.add(ae);
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tCOMA:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_14;
      }
      jj_consume_token(tCOMA);
      ae = expresion();
            if(ae != null)
                lpar.add(ae);
    }
      {if (true) return lpar;}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Symbol> parametros_declaraciones() throws ParseException {
    System.out.println("Par\u00e1metros declaraciones");
    AtribTipo aT;
    ArrayList<String> lVars;
    boolean isRef = false;
    ArrayList<Symbol> allSymbols = new ArrayList<Symbol>();
    aT = tipo();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tREF:
      jj_consume_token(tREF);
               isRef = true;
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    lVars = lista_ids();
        for (String id : lVars) {
            Symbol sV = null;
            if(aT.isArray) {
                sV = new SymbolArray(
                    id, 0, aT.size-1, aT.type, isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL);
            } else {
                switch(aT.type) {
                    case INT:
                        sV = new SymbolInt(
                            id,
                            isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL
                        );
                        break;
                    case BOOL:
                        sV = new SymbolBool(
                            id,
                            isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL
                        );
                        break;
                    case CHAR:
                        sV = new SymbolChar(
                            id,
                            isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL
                        );
                        break;
                    default:
                        System.out.println("Error: tipo no definido para variable \"" +
                            id + "\".");
                }
            }
            allSymbols.add(sV);
        }
        isRef = false;
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tSEMICOLON:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_15;
      }
      jj_consume_token(tSEMICOLON);
      aT = tipo();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tREF:
        jj_consume_token(tREF);
                   isRef = true;
        break;
      default:
        jj_la1[29] = jj_gen;
        ;
      }
      lVars = lista_ids();
        for (String id : lVars) {
                Symbol sV = null;
                if(aT.isArray) {
                    sV = new SymbolArray(
                        id, 0, aT.size-1, aT.type, isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL);
                } else {
                    switch(aT.type) {
                        case INT:
                            sV = new SymbolInt(
                                id,
                                isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL
                            );
                            break;
                        case BOOL:
                            sV = new SymbolBool(
                                id,
                                isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL
                            );
                            break;
                        case CHAR:
                            sV = new SymbolChar(
                                id,
                                isRef ? Symbol.ParameterClass.REF : Symbol.ParameterClass.VAL
                            );
                            break;
                        default:
                            System.out.println("Error: tipo no definido para variable \"" +
                                id + "\".");
                    }
                }
                allSymbols.add(sV);
            }
    }
      {if (true) return allSymbols;}
    throw new Error("Missing return statement in function");
  }

// --- INICIO DE instrucciones.jj ---
  static final public void instrucciones() throws ParseException {
  System.out.println("Instrucciones");
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tESCRIBIR_LIN:
      case tESCRIBIR:
      case tLEER_LIN:
      case tLEER:
      case tENTACAR:
      case tCARAENT:
      case tINTEGER:
      case tCHARACTER:
      case tBOOLEAN:
      case tSELECTION:
      case tITERATION:
      case tABANDONAR:
      case tNADA:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_16;
      }
      instruccion();
    }
  }

  static final public void instruccion() throws ParseException {
  System.out.println("Instrucci\u00f3n");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tESCRIBIR_LIN:
      escribir_linea();
      jj_consume_token(tSEMICOLON);
      break;
    case tESCRIBIR:
      escribir();
      jj_consume_token(tSEMICOLON);
      break;
    case tLEER_LIN:
      leer_linea();
      jj_consume_token(tSEMICOLON);
      break;
    case tLEER:
      leer();
      jj_consume_token(tSEMICOLON);
      break;
    case tENTACAR:
      entAcar();
      jj_consume_token(tSEMICOLON);
      break;
    case tCARAENT:
      carAent();
      jj_consume_token(tSEMICOLON);
      break;
    default:
      jj_la1[31] = jj_gen;
      if (jj_2_9(2)) {
        llamar_funcion();
      } else if (jj_2_10(2)) {
        asignacion();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tSELECTION:
          seleccion();
          break;
        case tITERATION:
          bucle();
          break;
        default:
          jj_la1[32] = jj_gen;
          if (jj_2_11(2)) {
            declaracion_procs_funcs();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case tABANDONAR:
              jj_consume_token(tABANDONAR);
              jj_consume_token(tSEMICOLON);
              break;
            case tNADA:
              jj_consume_token(tNADA);
              jj_consume_token(tSEMICOLON);
              break;
            default:
              jj_la1[33] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
  }

  static final public void seleccion() throws ParseException {
  System.out.println("Selecci\u00f3n");
    jj_consume_token(tSELECTION);
    label_17:
    while (true) {
      jj_consume_token(tCASE);
      expresion();
      jj_consume_token(tCOLON);
      instrucciones();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tCASE:
        ;
        break;
      default:
        jj_la1[34] = jj_gen;
        break label_17;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tOTHERWISE:
      jj_consume_token(tOTHERWISE);
      jj_consume_token(tCOLON);
      instrucciones();
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
    jj_consume_token(tEND_SELECTION);
  }

  static final public void bucle() throws ParseException {
  System.out.println("Bucle");
    jj_consume_token(tITERATION);
    expresion();
    instrucciones();
    jj_consume_token(tEND_ITERATION);
  }

// --- INICIO DE especiales.jj ---
  static final public void escribir_linea() throws ParseException {
    jj_consume_token(tESCRIBIR_LIN);
    jj_consume_token(tOPENING_PARENTHESIS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tENTACAR:
    case tCARAENT:
    case tTRUE:
    case tFALSE:
    case tSTRING:
    case tCHAR:
    case tCONSTANT:
    case tOPENING_PARENTHESIS:
    case tPLUS:
    case tMINUS:
    case tNOT:
    case tIDENTIFICADOR:
      escribir_params();
      break;
    default:
      jj_la1[36] = jj_gen;
      ;
    }
    jj_consume_token(tCLOSING_PARENTHESIS);
  }

  static final public void escribir() throws ParseException {
    jj_consume_token(tESCRIBIR);
    jj_consume_token(tOPENING_PARENTHESIS);
    escribir_params();
    jj_consume_token(tCLOSING_PARENTHESIS);
  }

  static final public void escribir_params() throws ParseException {
    AtribExp a;
    a = expresion_simple();
        if (a.type == Symbol.Types.ARRAY || a.type == Symbol.Types.PROCEDURE || a.type == Symbol.Types.UNDEFINED) {
            String errorMsg = String.format("Error en expresi\u00f3n: tipo de dato inv\u00e1lido encontrado. Tipo recibido: %s.", a.type);
            System.out.println("Error en escribir_params: " + errorMsg);
        }
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tCOMA:
        ;
        break;
      default:
        jj_la1[37] = jj_gen;
        break label_18;
      }
      jj_consume_token(tCOMA);
      a = expresion_simple();
            if (a.type == Symbol.Types.ARRAY || a.type == Symbol.Types.PROCEDURE || a.type == Symbol.Types.UNDEFINED) {
                String errorMsg = String.format("Error en expresi\u00f3n: tipo de dato inv\u00e1lido encontrado. Tipo recibido: %s.", a.type);
                System.out.println("Error en escribir_params: " + errorMsg);
            }
    }
  }

  static final public void leer_linea() throws ParseException {
     ArrayList<String> lVars = new ArrayList<String>();
     Symbol s;
    jj_consume_token(tLEER_LIN);
    jj_consume_token(tOPENING_PARENTHESIS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tIDENTIFICADOR:
      lVars = lista_ids();
            for (String i : lVars) {
                s = st.getSymbol(i);
                if (s.type == Symbol.Types.ARRAY || s.type == Symbol.Types.PROCEDURE || s.type == Symbol.Types.UNDEFINED) {
                    String errorMsg = String.format("Error en leer_linea: el tipo de variable '%s' no es v\u00e1lido. Tipo encontrado: %s.", i, s.type);
                    System.out.println(errorMsg);
                }
            }
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
    jj_consume_token(tCLOSING_PARENTHESIS);
  }

  static final public void leer() throws ParseException {
     ArrayList<String> lVars = new ArrayList<String>();
     Symbol s;
    jj_consume_token(tLEER);
    jj_consume_token(tOPENING_PARENTHESIS);
    lVars = lista_ids();
        for (String i : lVars) {
            s = st.getSymbol(i);
            if (s.type == Symbol.Types.ARRAY || s.type == Symbol.Types.PROCEDURE || s.type == Symbol.Types.UNDEFINED) {
                String errorMsg = String.format("Error en leer: el tipo de variable '%s' no es v\u00e1lido. Tipo encontrado: %s.", i, s.type);
                System.out.println(errorMsg);
            }
        }
    jj_consume_token(tCLOSING_PARENTHESIS);
  }

  static final public void entAcar() throws ParseException {
    AtribExp i;
    jj_consume_token(tENTACAR);
    jj_consume_token(tOPENING_PARENTHESIS);
    i = expresion_simple();
        if (i.type != Symbol.Types.INT) {
            String errorMsg = String.format("Error en entAcar: tipo de expresi\u00f3n incorrecto. Se esperaba tipo INT, pero se encontr\u00f3: %s.", i.type);
            System.out.println(errorMsg);
        }
    jj_consume_token(tCLOSING_PARENTHESIS);
  }

  static final public void carAent() throws ParseException {
    AtribExp c;
    jj_consume_token(tCARAENT);
    jj_consume_token(tOPENING_PARENTHESIS);
    c = primario();
        if (c.type != Symbol.Types.CHAR) {
            String errorMsg = String.format("Error en carAent: tipo de expresi\u00f3n incorrecto. Se esperaba tipo CHAR, pero se encontr\u00f3: %s.", c.type);
            System.out.println(errorMsg);
        }
    jj_consume_token(tCLOSING_PARENTHESIS);
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(tCOMA)) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    if (jj_scan_token(tOPENING_PARENTHESIS)) return true;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_scan_token(tCONSTANT)) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_3R_58()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_3R_57()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    Token xsp;
    if (jj_3_3()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_3()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_scan_token(tINTEGER)) return true;
    return false;
  }

  static private boolean jj_3_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) return true;
    }
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_scan_token(tBOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_scan_token(tCHARACTER)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_3R_41()) return true;
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) return true;
    }
    }
    if (jj_scan_token(tOPENING_SQUARE_BRACKET)) return true;
    if (jj_3R_45()) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_scan_token(tBOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_scan_token(tCHARACTER)) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_scan_token(tINTEGER)) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_scan_token(tOPENING_PARENTHESIS)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_41()) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_scan_token(tOPENING_SQUARE_BRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_scan_token(tCARAENT)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) jj_scanpos = xsp;
    if (jj_scan_token(tASSIGN)) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) return true;
    }
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_3R_44()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_scan_token(tENTACAR)) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    if (jj_scan_token(tOPENING_PARENTHESIS)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_scan_token(tFALSE)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    if (jj_scan_token(tOPENING_SQUARE_BRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(tIDENTIFICADOR)) return true;
    if (jj_scan_token(tOPENING_PARENTHESIS)) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) return true;
    }
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_scan_token(tTRUE)) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    Token xsp;
    if (jj_3R_33()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_scan_token(tSTRING)) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_29()) return true;
    if (jj_3R_30()) return true;
    if (jj_scan_token(tSEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_scan_token(tCHAR)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public gclTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  /** Whether we are looking ahead. */
  static private boolean jj_lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[39];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x70000,0x70000,0x70000,0x70000,0x0,0x0,0x6000,0x8c000000,0x0,0x0,0x8c006000,0x0,0x0,0x0,0x0,0x0,0x8c006000,0x0,0x0,0x70000,0x70000,0x70000,0x70000,0x70000,0x70000,0x8c006000,0x0,0x8000,0x0,0x8000,0x604f7e00,0x7e00,0x480000,0x60000000,0x200000,0x10000000,0x8c006000,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x4000000,0x0,0x0,0x0,0x4,0x40,0x0,0x4000003,0x41800,0x41800,0x4000203,0xe000,0x1800,0x1f80000,0x30000,0x30000,0x4041a03,0xe000,0x1f80000,0x4000000,0x4000000,0x0,0x4000000,0x0,0x4000000,0x4041a03,0x4,0x0,0x8,0x0,0x4000000,0x0,0x0,0x0,0x0,0x0,0x4041a03,0x4,0x4000000,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[11];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public gcl(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public gcl(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new gclTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public gcl(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new gclTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public gcl(gclTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(gclTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[60];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 39; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 60; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 11; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
