/* Generated By:JavaCC: Do not edit this line. gclConstants.java */
package traductor;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gclConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int tPROGRAMA = 8;
  /** RegularExpression Id. */
  int tREF = 9;
  /** RegularExpression Id. */
  int tINTEGER = 10;
  /** RegularExpression Id. */
  int tCHARACTER = 11;
  /** RegularExpression Id. */
  int tBOOLEAN = 12;
  /** RegularExpression Id. */
  int tSELECTION = 13;
  /** RegularExpression Id. */
  int tEND_SELECTION = 14;
  /** RegularExpression Id. */
  int tCASE = 15;
  /** RegularExpression Id. */
  int tITERATION = 16;
  /** RegularExpression Id. */
  int tEND_ITERATION = 17;
  /** RegularExpression Id. */
  int tBEGGINING = 18;
  /** RegularExpression Id. */
  int tEND = 19;
  /** RegularExpression Id. */
  int tTRUE = 20;
  /** RegularExpression Id. */
  int tFALSE = 21;
  /** RegularExpression Id. */
  int tOTHERWISE = 22;
  /** RegularExpression Id. */
  int tABANDONAR = 23;
  /** RegularExpression Id. */
  int tNADA = 24;
  /** RegularExpression Id. */
  int tSTRING = 25;
  /** RegularExpression Id. */
  int tCHAR = 26;
  /** RegularExpression Id. */
  int tCONSTANT = 27;
  /** RegularExpression Id. */
  int tCOMA = 28;
  /** RegularExpression Id. */
  int tSEMICOLON = 29;
  /** RegularExpression Id. */
  int tUNDERSCORE = 30;
  /** RegularExpression Id. */
  int tASSIGN = 31;
  /** RegularExpression Id. */
  int tOPENING_SQUARE_BRACKET = 32;
  /** RegularExpression Id. */
  int tCLOSING_SQUARE_BRACKET = 33;
  /** RegularExpression Id. */
  int tCOLON = 34;
  /** RegularExpression Id. */
  int tOPENING_PARENTHESIS = 35;
  /** RegularExpression Id. */
  int tCLOSING_PARENTHESIS = 36;
  /** RegularExpression Id. */
  int tPLUS = 37;
  /** RegularExpression Id. */
  int tMINUS = 38;
  /** RegularExpression Id. */
  int tTIMES = 39;
  /** RegularExpression Id. */
  int tDIVIDE = 40;
  /** RegularExpression Id. */
  int tMOD = 41;
  /** RegularExpression Id. */
  int tAND = 42;
  /** RegularExpression Id. */
  int tOR = 43;
  /** RegularExpression Id. */
  int tNOT = 44;
  /** RegularExpression Id. */
  int tGT = 45;
  /** RegularExpression Id. */
  int tGE = 46;
  /** RegularExpression Id. */
  int tLT = 47;
  /** RegularExpression Id. */
  int tLE = 48;
  /** RegularExpression Id. */
  int tEQUAL = 49;
  /** RegularExpression Id. */
  int tNOTEQUAL = 50;
  /** RegularExpression Id. */
  int tDOT = 51;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 52;
  /** RegularExpression Id. */
  int tOTHER = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<LETTER>",
    "<DIGIT>",
    "\"Programa\"",
    "\"ref\"",
    "\"entero\"",
    "\"caracter\"",
    "\"booleano\"",
    "\"Sel\"",
    "\"Fsel\"",
    "\"caso\"",
    "\"Mq\"",
    "\"FMq\"",
    "\"Principio\"",
    "\"Fin\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"dlc\"",
    "\"abandonar\"",
    "\"nada\"",
    "<tSTRING>",
    "<tCHAR>",
    "<tCONSTANT>",
    "\",\"",
    "\";\"",
    "\"_\"",
    "\":=\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"<>\"",
    "\".\"",
    "<tIDENTIFICADOR>",
    "<tOTHER>",
  };

}
